version: '3'
services:

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: sit722_part3_qxdp_user
      POSTGRES_PASSWORD: Owm7kCzRK4JyGTtMHWzKfQuHtQ9y2B7p
      POSTGRES_DB: sit722_part3_qxdp 
    ports:
      - "5432:5432"
    restart: "on-failure"

  book-catalog: 
    platform: linux/amd64
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://sit722_part3_qxdp_user:Owm7kCzRK4JyGTtMHWzKfQuHtQ9y2B7p@db:5432/sit722_part3_qxdp
    restart: "on-failure"

  inventory-management: 
    platform: linux/amd64  
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - DATABASE_URL=postgresql://sit722_part3_qxdp_user:Owm7kCzRK4JyGTtMHWzKfQuHtQ9y2B7p@db:5432/sit722_part3_qxdp
    depends_on:
      - db
    restart: "on-failure"
